server:
  port: 8091
spring:
  application:
    name: user-service
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 127.0.0.1
    username: engineer
    password: engineer
    virtual-host: /engineer
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1 # 连接池最大等待时间 -1 没有限制:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/engineer-user?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
      username: root
      password: 326liyinjie
      initialSize: 5 #初始化连接大小
      minIdle: 5     #最小连接池数量
      maxActive: 20  #最大连接池数量
      maxWait: 60000 #获取连接时最大等待时间，单位毫秒
      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000   #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 from DUAL  #测试连接
      testWhileIdle: true                  #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      testOnBorrow: false                  #获取连接时执行检测，建议关闭，影响性能
      testOnReturn: false                  #归还连接时执行检测，建议关闭，影响性能
      poolPreparedStatements: false        #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      maxPoolPreparedStatementPerConnectionSize: 20 #开启poolPreparedStatements后生效
      filters: stat,wall #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000' #通过connectProperties属性来打开mergeSql功能;慢SQL记录
mybatis:
  type-aliases-package: com.engineer.user.pojo
  mapper-locations: classpath:com/engineer/user/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #开启驼峰命名
    jdbc-type-for-null: NULL
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    cache-enabled: false #二级缓存
    call-setters-on-nulls: true #map空列不显示问题
mapper:
  mappers: com.engineer.common.mapper.BaseMapper
  not-empty: false
  identity: MYSQL
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
engineer:
  worker:
    workerId: 1
    dataCenterId: 1
  sms:
    exchange: engineer.sms.exchange
    routingKey: sms.verify.code
    codeTimeOut: 5